# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_editor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=datetime.datetime(2019, 6, 13, 8, 59, 42, 796, tzinfo=utc), upload_to='articles/'),
            preserve_default=False,
        ),
    ]
